apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-price-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-price-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cloud-price-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-metrics
      port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
